parameters:
  orkestra.solr.connection: [ ]
  orkestra.solr.metadata.factory.class: Metadata\MetadataFactory

services:
  orkestra.solr:
    class: SolrClient
    arguments: [ %orkestra.solr.connection% ]
  orkestra.solr.metadata.driver:
    class: Metadata\Driver\DriverChain
  orkestra.solr.metadata.factory:
    class: %orkestra.solr.metadata.factory.class%
    arguments: [ @orkestra.solr.metadata.driver ]
  orkestra.solr.document_manager:
    class: Orkestra\Bundle\SolrBundle\DocumentManager
    arguments: [ @orkestra.solr, @orkestra.solr.metadata.factory ]
