parameters:

services:
  orkestra.solr:
    class: SolrClient
  orkestra.solr.metadata.driver:
    class: Metadata\Driver\DriverChain
  orkestra.solr.metadata.factory:
    class: Metadata\ClassMetadataFactory
    arguments: [ @orkestra.solr.metadata.driver ]
